### ISSUE TITLE
It doesn't render in the API

### ISSUE THREAD

**Issue by ivanandresdiaz** [remotion-dev/github-unwrapped-2021#1]
src/get-render-or-make.ts

import {
  AwsRegion,
  getFunctions,
  renderMediaOnLambda,
  RenderProgress,
} from "@remotion/lambda";

`const [first] = await getFunctions({
      compatibleOnly: true,
      region,
    });
    console.log(`Username=${username} Account=${account} Region=${region}`);
    await lockRender(region, username, account, first.functionName);

    const { renderId, bucketName } = await renderMediaOnLambda({
      region: region,
      functionName: first.functionName,
      serveUrl: SITE_ID,
      composition: COMP_NAME,
      inputProps: { stats: stats },
      codec: "h264-mkv",
      imageFormat: "jpeg",
      maxRetries: 1,
      framesPerLambda: 80,
      privacy: "public",
    });
    _renderId = renderId;
    _region = region;
    await saveRender({
      region: region,
      bucketName,
      renderId,
      username,
    });`
getFunctions() returns an empty array (I have added de .env variables AWS_KEY_1,AWS_SECRET_1) . 

And the page https://www.githubunwrapped.com/ doesn't render API to download it. 
 
in the UI shows the next message: "Oops, sorry the render failed! We will fix all render bugs, so come back tomorrow and it should be fixed! Or just press the retry button which will work most of the time"

**Comment by JonnyBurger** [comment]
Thanks a lot for reporting!

This is due to a AWS Lambda environment change that is handled in a newer version of Remotion Lambda! It is currently redeploying and will work again very soon.
