### ISSUE TITLE
Feature Request: select timeframe 

### ISSUE THREAD

**Issue by muescha** [remotion-dev/github-unwrapped-2021#4]
i would like to select a time frame for the analysis.

i have not so many commits / PR in the last year - but i would like to see for example one year from April 2019 onwards :)

**Comment by JonnyBurger** [comment]
Also for this years version, we will keep the options limited and only use the 2022 data.
The purpose is to make a light experience that works for everyone, even if they have few commits.

This means we will not have many knobs and sliders but of course anyone is free to take it and make a more sophisticated version.
